export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
export JRE_HOME=${JAVA_HOME}
export DSE_HOME=${HOME}/dse

export PATH=${DSE_HOME}/bin:/usr/local/bin:/usr/local/sbin:${PATH}
export MAVEN_OPTS='-Xms512m -Xmx2048m -Djava.awt.headless=true'

export LSCOLORS='Bxgxfxfxcxdxdxhbadbxbx'
export LS_OPTIONS='--color=auto'
export CLICOLOR='Yes'
export LSCOLORS=''
export EDITOR=/usr/local/bin/vim
export HISTCONTROL=ignoredups
set -o emacs

# Source stuff that shouldn't be on github :-)
. ~/.secret_bashrc

source ~/dotfiles/maven/maven-completion.bash
source /usr/local/etc/bash_completion.d/git-completion.bash
complete -C aws_completer aws

source ~/.shell_prompt.sh

tstart () {
  cd ~/Documents/workspace/Treasury/top-ng
  ./commands/add_my_ip_to_security_group.sh
  git up
}

alias bu="brew update && brew doctor && brew upgrade"

alias vpnon="scutil --nc start ElementVPN --secret 3bmshtr"
alias vpnoff="scutil --nc stop ElementVPN"
